"""Connect this repository to Codex through a project-scoped MCP configuration."""
import json
import pathlib
import shutil
import sys
from server import API, ROOT, execute


def configure(root, command, server):
    config = root / '.codex' / 'config.toml'
    body = ('# Local Relay evidence tools. Generated by integrations/relay-tools/connect.py.\n'
            '[mcp_servers.repro-relay]\n'
            'command = ' + json.dumps(command) + '\n'
            'args = [' + json.dumps(server) + ']\n')
    if config.parent.is_symlink() or config.is_symlink():
        raise ValueError('Project configuration symlinks are not modified by this setup.')
    config.parent.mkdir(exist_ok=True)
    try:
        with config.open('x', encoding='utf-8') as stream:
            stream.write(body)
    except FileExistsError:
        if config.read_text(encoding='utf-8') == body:
            return False
        raise ValueError('A project Codex configuration already exists. It was not replaced. See the manual setup in integrations/relay-tools/README.md.')
    return True


def main():
    status = execute(API('http://127.0.0.1:8178/api/v1'), 'relay_workspace_status', {})
    if not shutil.which('codex'):
        raise SystemExit('Codex CLI was not found. See integrations/relay-tools/README.md for generic MCP setup.')
    server = str(pathlib.Path(__file__).with_name('server.py').resolve())
    try:
        created = configure(ROOT, sys.executable, server)
    except ValueError as error:
        raise SystemExit(str(error))
    print('Relay project MCP configuration ' + ('created' if created else 'already present') + ' for ' + (status['repository'] or 'the local workspace') + '.')
    print('Open a new Codex session in this trusted repository to load the tools. Global settings and tool approval policy were not changed.')


if __name__ == '__main__':
    main()
