import { test, expect } from '@playwright/test'
test('public visitors get isolated workspaces and can leave feedback',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Welcome to Repro Relay'})).toBeVisible()
  await page.screenshot({path:'test-results/public-landing.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Try a test workspace',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Investigation overview',exact:true})).toBeVisible()
  const cases=await (await page.request.get('/api/v1/cases')).json()
  const firstId=cases[0].id
  await page.getByRole('button',{name:'Give feedback',exact:true}).click()
  await page.getByRole('radio',{name:'Yes',exact:true}).check()
  await page.getByLabel('What worked, or what is missing?').fill('The build freshness check was useful. I would like a real investigation next.')
  await page.getByRole('button',{name:'Send feedback',exact:true}).click()
  await expect(page.getByText('Feedback saved for the project team.')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button',{name:'New report',exact:true})).toBeEnabled()
  const reloadCases=await (await page.request.get('/api/v1/cases')).json();expect(reloadCases[0].id).toBe(firstId)
  const visitor=await browser.newContext({baseURL:'http://127.0.0.1:5190'})
  const second=await visitor.newPage();await second.goto('/')
  await second.getByRole('button',{name:'Try a test workspace',exact:true}).click()
  await expect(second.getByRole('button',{name:'New report',exact:true})).toBeEnabled()
  const otherCases=await(await second.request.get('/api/v1/cases')).json();expect(otherCases[0].id).not.toBe(firstId)
  expect((await second.request.get(`/api/v1/cases/${firstId}`)).status()).toBe(404)
  await second.setViewportSize({width:390,height:844})
  await expect.poll(()=>second.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.close();expect(errors).toEqual([])
})

test('PaceUI dashboard, agent controls, themes, keyboard tabs, and mobile navigation', async ({page}) => {
  await page.emulateMedia({colorScheme:'light', reducedMotion:'reduce'})
  await page.goto('/')
  await page.getByRole('button',{name:'Switch to dark theme'}).click()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark')
  await page.screenshot({path:'test-results/landing-dark.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:320,height:740})
  await page.screenshot({path:'test-results/landing-mobile.png',fullPage:true,animations:'disabled'})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.setViewportSize({width:1440,height:960})
  await page.getByRole('button',{name:'Try a test workspace',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Investigation overview'})).toBeVisible()
  await page.screenshot({path:'test-results/paceui-overview-dark.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Switch to light theme'}).click()
  await page.screenshot({path:'test-results/paceui-overview-light.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'Switch to dark theme'}).click()
  await page.getByRole('button',{name:'Agent controls',exact:true}).click()
  await expect(page.getByRole('region',{name:'Agent investigation'})).toBeVisible()
  await page.getByRole('button',{name:'Case inbox',exact:true}).click()
  await page.locator('.case-row').first().click()
  await expect(page.getByRole('navigation',{name:'Case progress'})).toBeVisible()
  await page.getByRole('tab',{name:/Evidence/}).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab',{name:'Agent context',exact:true})).toBeFocused()
  await expect(page.getByRole('region',{name:'Role context'})).toBeVisible()
  await page.screenshot({path:'test-results/workspace-dark.png',fullPage:true,animations:'disabled'})
  await page.getByRole('button',{name:'New report',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).not.toBeVisible()
  await expect(page.getByRole('button',{name:'New report',exact:true})).toBeFocused()
  await page.getByRole('button',{name:'Switch to light theme'}).click()
  await page.getByRole('tab',{name:/Evidence/}).click()
  await page.screenshot({path:'test-results/workspace-light.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  await page.getByRole('button',{name:/All reports/}).click()
  await expect(page.getByRole('region',{name:'Cases',exact:true})).toBeVisible()
  await expect(page.getByRole('region',{name:'Selected case'})).not.toBeVisible()
  await page.locator('.case-row').first().click()
  await expect(page.getByRole('region',{name:'Selected case'})).toBeVisible()
  await page.screenshot({path:'test-results/workspace-mobile.png',fullPage:true,animations:'disabled'})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.getByRole('button',{name:'Toggle Sidebar',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Sidebar'})).toBeVisible()
  await page.getByRole('button',{name:'Overview',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Sidebar'})).not.toBeVisible()
  await expect(page.getByRole('heading',{name:'Investigation overview'})).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/paceui-overview-mobile.png',fullPage:true,animations:'disabled'})
})
