import { test, expect } from '@playwright/test'
test('public visitors get isolated workspaces and can leave feedback',async({page,browser})=>{
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'A bug report is only the beginning.'})).toBeVisible()
  await page.screenshot({path:'test-results/public-landing.png',fullPage:true})
  await page.getByRole('button',{name:'Try a test workspace',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Demo: CSV export stops after changing dates',exact:true}).last()).toBeVisible()
  const cases=await (await page.request.get('/api/v1/cases')).json()
  const firstId=cases[0].id
  await page.getByRole('button',{name:'Give feedback',exact:true}).click()
  await page.getByRole('radio',{name:'Yes',exact:true}).check()
  await page.getByLabel('What worked, or what is missing?').fill('The build freshness check was useful. I would like a real investigation next.')
  await page.getByRole('button',{name:'Send feedback',exact:true}).click()
  await expect(page.getByText('Feedback saved for the project team.')).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button',{name:'New report',exact:true})).toBeEnabled()
  const reloadCases=await (await page.request.get('/api/v1/cases')).json();expect(reloadCases[0].id).toBe(firstId)
  const visitor=await browser.newContext({baseURL:'http://127.0.0.1:5190'})
  const second=await visitor.newPage();await second.goto('/')
  await second.getByRole('button',{name:'Try a test workspace',exact:true}).click()
  await expect(second.getByRole('button',{name:'New report',exact:true})).toBeEnabled()
  const otherCases=await(await second.request.get('/api/v1/cases')).json();expect(otherCases[0].id).not.toBe(firstId)
  expect((await second.request.get(`/api/v1/cases/${firstId}`)).status()).toBe(404)
  await second.setViewportSize({width:390,height:844})
  expect(await second.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
  await visitor.close();expect(errors).toEqual([])
})
