import { test, expect } from '@playwright/test'

test('appearance persists, navigation works on phone, and setup remains connected to Relay', async ({page}) => {
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/?view=connections')
  const trigger=page.getByRole('button',{name:'Customize appearance'})
  await trigger.click()
  const panel=page.getByRole('dialog',{name:'Appearance'})
  await panel.getByLabel('Accent color').selectOption('teal')
  await panel.getByLabel('Sidebar layout').selectOption('floating')
  await panel.getByRole('combobox',{name:'Density',exact:true}).selectOption('compact')
  await panel.getByLabel('Text size').selectOption('120')
  await panel.getByLabel('Reduce motion',{exact:true}).check()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-accent','teal')
  await expect(page.locator('html')).toHaveAttribute('data-motion','reduce')
  await expect(page.locator('.configuration-background')).toHaveCount(0)
  await page.getByRole('button',{name:'Collapse sidebar',exact:true}).click()
  await page.getByRole('navigation',{name:'Workspace',exact:true}).getByRole('button',{name:'Knowledge',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Project memory',exact:true})).toBeVisible()
  await page.setViewportSize({width:320,height:844})
  const phone=page.getByRole('navigation',{name:'Phone navigation'})
  await phone.getByRole('button',{name:'Usage',exact:true}).click()
  await expect(page.getByRole('region',{name:'Workspace usage'})).toBeVisible()
  await phone.getByRole('button',{name:'Team',exact:true}).click()
  await expect(page.getByRole('region',{name:'Account and team'})).toBeVisible()
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await trigger.click()
  expect(await panel.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
  await page.screenshot({path:'test-results/reptest-appearance-mobile.png'})
  await panel.getByRole('button',{name:'Reset appearance'}).click()
  await page.keyboard.press('Escape')
  await phone.getByRole('button',{name:'Settings',exact:true}).click()
  await expect(page.getByRole('region',{name:'Agent tools library'})).toBeVisible()
  expect(errors).toEqual([])
})

test('Usage shows case-bound telemetry and excludes prototype and local-validation spending', async ({page}) => {
  const response=await page.request.post('/api/v1/cases',{data:{title:`Reptest usage fixture ${Date.now()}`,project:'Reptest fixture',url:'https://example.com',description:'UI telemetry fixture',expected:'Show real source values',build:'fixture-build'}})
  expect(response.ok()).toBe(true)
  const item=await response.json()
  const base={case_id:item.id,case_revision:1,owner_version:1,build:item.build,version:1,status:'completed',created_at:'2026-09-14T12:00:00Z',checked_at:'2026-09-14T12:01:00Z',max_seconds:120,context:{},events:[]}
  let failed=false
  await page.route(`**/cases/${item.id}/runs`,r=>failed?r.fulfill({status:503,json:{detail:'Fixture usage unavailable'}}):r.fulfill({json:[{...base,id:'RUN-usage-one',usage:{total_tokens:42,cost_usd:0}},{...base,id:'RUN-usage-unknown',usage:{total_tokens:12}},{...base,id:'RUN-usage-local',execution_kind:'local_validation',usage:{cost_usd:999}}]}))
  await page.goto(`/?view=usage&case=${item.id}`)
  const inspector=page.getByRole('region',{name:'Investigation cost inspector'})
  await expect(inspector.locator('.cost-total strong')).toHaveText('$0.00')
  await expect(page.getByLabel('Investigation attempt').getByRole('option')).toHaveCount(2)
  await page.getByLabel('Investigation attempt').selectOption('RUN-usage-unknown')
  await expect(inspector.locator('.cost-total strong')).toHaveText('Not reported')
  failed=true
  await expect(page.getByRole('alert').filter({hasText:'Fixture usage unavailable'})).toBeVisible({timeout:10000})
  failed=false
  await page.getByRole('button',{name:'Retry usage'}).click()
  await expect(page.getByRole('alert').filter({hasText:'Fixture usage unavailable'})).toHaveCount(0)
  await page.screenshot({path:'test-results/reptest-usage-desktop.png',fullPage:true})
  await page.getByRole('button',{name:'Open investigation',exact:true}).click()
  await expect(page).toHaveURL(new RegExp(`view=agents.*case=${item.id}|case=${item.id}.*view=agents`))
})
