import { test, expect } from '@playwright/test'

test('reviewed corrections reach one follow-up without replacing source evidence, and selection survives reload', async ({page}) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')

  async function create(title: string) {
    await page.getByRole('button', {name: 'New report', exact: true}).click()
    const dialog = page.getByRole('dialog')
    await dialog.getByLabel('Report title').fill(title)
    await dialog.getByLabel('Project', {exact: true}).fill('Runner browser fixture')
    await dialog.getByLabel('Application URL').fill('https://example.com')
    await dialog.getByLabel('Current build').fill('fixture-a')
    await dialog.getByLabel('Reported behavior').fill('Controlled fixture report; no real application was tested.')
    await dialog.getByLabel('Expected behavior').fill('Export a CSV')
    const saved = page.waitForResponse(response => response.url().endsWith('/api/v1/cases') && response.request().method() === 'POST')
    await dialog.getByRole('button', {name: 'Save report', exact: true}).click()
    const response = await saved
    expect(response.ok()).toBe(true)
    const item = await response.json()
    await expect(dialog).not.toBeVisible()
    await page.getByRole('button', {name: 'Agent controls', exact: true}).click()
    return item
  }

  const item = await create(`Runner fixture ${Date.now()}`)
  const workspace = page.getByRole('region', {name: 'Investigation workspace', exact: true})
  const panel = page.getByRole('region', {name: 'Agent investigation', exact: true})
  await expect(workspace.getByRole('button', {name: 'Start Hermes investigation', exact: true})).toBeEnabled()
  const admitted = page.waitForResponse(response => response.url().endsWith(`/cases/${item.id}/runs`) && response.request().method() === 'POST')
  await workspace.getByRole('button', {name: 'Start Hermes investigation', exact: true}).click()
  const original = await (await admitted).json()
  await expect(panel.getByRole('status')).toHaveText(/Queued|Submitting to Hermes|Investigating/)
  await page.reload()
  await expect(page.getByRole('heading', {name: 'Agent controls', exact: true})).toBeVisible()
  await expect(panel.getByRole('status')).toHaveText('Result ready for review', {timeout: 20_000})
  await expect(panel).toContainText('Controlled fixture proposal')
  await expect(workspace).toContainText('42')
  await expect(workspace).toContainText('Not reported')
  const cost = workspace.getByRole('region', {name: 'Investigation cost inspector'})
  await expect(cost).toContainText('$0.002')
  await expect(cost).toContainText('fixture-model')
  await cost.getByText('Usage reporting history', {exact:true}).click()
  await expect(cost).toContainText('changed reports retained')
  const downloadPromise = page.waitForEvent('download')
  await cost.getByRole('button', {name: 'Download cost report'}).click()
  const download = await downloadPromise
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []; for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  const report = JSON.parse(Buffer.concat(chunks).toString())
  expect(report.run_id).toBe(original.id)
  expect(report.usage.cost_usd).toBe(0.002)
  expect(report.usage_audit.receipts.length).toBeGreaterThan(0)
  expect(report.case_coverage).toMatchObject({runs:1,runs_with_cost:1,reported_subtotal_usd:0.002})
  expect(report.context_hash).toMatch(/^[a-f0-9]{64}$/)
  await page.screenshot({path:'test-results/hermes-cost-inspector.png',fullPage:true})
  await expect(panel).toContainText('No real browser actions were executed.')
  const originalRunsResponse = await page.request.get(`/api/v1/cases/${item.id}/runs`)
  expect(originalRunsResponse.ok()).toBe(true)
  const [completedOriginal] = await originalRunsResponse.json()

  // A rejected save must leave the review draft intact and allow an explicit retry.
  const reviewer = 'Runner fixture reviewer'
  const feedback = 'Check the date filter before blaming the export route'
  await workspace.getByRole('combobox', {name: 'Review decision', exact: true}).selectOption('needs_changes')
  await workspace.getByRole('textbox', {name: 'Reviewer name', exact: true}).fill(reviewer)
  await workspace.getByRole('textbox', {name: 'Review feedback', exact: true}).fill(feedback)
  const reviewUrl = `**/api/v1/runs/${original.id}/reviews`
  await page.route(reviewUrl, route => route.fulfill({status: 503, contentType: 'application/json', body: JSON.stringify({detail: 'Fixture save unavailable. Retry this review.'})}), {times: 1})
  await workspace.getByRole('button', {name: 'Save review', exact: true}).click()
  await expect(workspace.getByRole('alert').filter({hasText: 'Fixture save unavailable'})).toBeVisible()
  await expect(workspace.getByRole('button', {name: 'Save review', exact: true})).toHaveAttribute('data-approval-state', 'error')
  await expect(workspace.getByRole('textbox', {name: 'Reviewer name', exact: true})).toHaveValue(reviewer)
  await expect(workspace.getByRole('textbox', {name: 'Review feedback', exact: true})).toHaveValue(feedback)
  const savedReview = page.waitForResponse(response => response.url().endsWith(`/runs/${original.id}/reviews`) && response.request().method() === 'POST')
  await workspace.getByRole('button', {name: 'Retry pending request', exact: true}).click()
  const reviewResponse = await savedReview
  expect(reviewResponse.ok()).toBe(true)
  const review = await reviewResponse.json()
  expect(review).toMatchObject({reviewer, feedback, decision: 'needs_changes', run_id: original.id})
  await expect(workspace.getByRole('button', {name: 'Save review', exact: true})).toHaveAttribute('data-approval-state', 'success')
  await expect(workspace.getByRole('button', {name: 'Save review', exact: true})).toBeDisabled()

  await expect(workspace.getByRole('button', {name: 'Start follow-up investigation', exact: true})).toBeEnabled()
  const previewResponse = await page.request.get(`/api/v1/cases/${item.id}/investigation-preview?review_id=${review.id}`)
  expect(previewResponse.ok()).toBe(true)
  const preview = await previewResponse.json()
  const packet = workspace.getByText('Exact context packet', {exact: true}).locator('..').locator('pre')
  await expect(packet).toContainText(feedback)
  expect(JSON.parse(await packet.innerText())).toEqual(preview.context)
  expect(preview.context.follow_up).toMatchObject({source_run_id: original.id, proposal: completedOriginal.output, review: {id: review.id, reviewer, feedback}})

  // Exercise the corrective action on a phone-sized viewport against the same persisted case.
  await page.setViewportSize({width: 390, height: 844})
  await workspace.getByRole('combobox', {name: 'Investigation time limit', exact: true}).selectOption('30')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  const followed = page.waitForResponse(response => response.url().endsWith(`/cases/${item.id}/runs`) && response.request().method() === 'POST')
  await workspace.getByRole('button', {name: 'Start follow-up investigation', exact: true}).click()
  const followResponse = await followed
  expect(followResponse.ok()).toBe(true)
  const followUp = await followResponse.json()
  expect(followResponse.request().postDataJSON()).toMatchObject({follow_up_review_id: review.id, context_hash: preview.context_hash, max_seconds: 30})
  expect(followUp.context).toEqual(preview.context)
  await expect(panel.getByRole('status')).toHaveText('Result ready for review', {timeout: 20_000})
  await expect(panel).toContainText('Controlled fixture follow-up proposal')
  await expect(panel).toContainText(feedback)
  await expect(workspace.getByRole('combobox', {name: 'Investigation history', exact: true})).toHaveValue(followUp.id)
  await page.reload()
  await expect(workspace.getByRole('combobox', {name: 'Investigation history', exact: true})).toHaveValue(followUp.id)
  await expect(panel).toContainText('Controlled fixture follow-up proposal')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({path: 'test-results/runner-artifacts/result-mobile.png', fullPage: true, animations: 'disabled'})

  await workspace.getByRole('combobox', {name: 'Investigation history', exact: true}).selectOption(original.id)
  await page.reload()
  await expect(workspace.getByRole('combobox', {name: 'Investigation history', exact: true})).toHaveValue(original.id)
  await expect(panel).toContainText(completedOriginal.output)
  await expect(panel).toContainText(feedback)
  const finalRunsResponse = await page.request.get(`/api/v1/cases/${item.id}/runs`)
  expect(finalRunsResponse.ok()).toBe(true)
  const finalRuns = await finalRunsResponse.json()
  expect(finalRuns).toHaveLength(2)
  expect(finalRuns.find((run: {id: string}) => run.id === original.id)).toMatchObject({output: completedOriginal.output, context: completedOriginal.context})
  const reviewsResponse = await page.request.get(`/api/v1/cases/${item.id}/run-reviews`)
  expect(reviewsResponse.ok()).toBe(true)
  expect(await reviewsResponse.json()).toEqual([review])
  const caseResponse = await page.request.get(`/api/v1/cases/${item.id}`)
  expect(caseResponse.ok()).toBe(true)
  const retained = await caseResponse.json()
  expect(retained.revision).toBe(item.revision)
  expect(retained.observations).toEqual(item.observations)

  await page.setViewportSize({width: 1440, height: 960})
  await page.screenshot({path: 'test-results/runner-artifacts/result-desktop.png', fullPage: true, animations: 'disabled'})
  await create(`Hold fixture ${Date.now()}`)
  await workspace.getByRole('button', {name: 'Start Hermes investigation', exact: true}).click()
  await expect(panel.getByRole('status')).toHaveText('Investigating', {timeout: 15_000})
  await workspace.getByRole('button', {name: 'Request stop', exact: true}).click()
  await expect(panel.getByRole('status')).toHaveText('Stopped', {timeout: 15_000})
  expect(errors).toEqual([])
})
