import { test, expect } from '@playwright/test'

test('a connected runtime progresses across reload, retains a proposal, and confirms cancellation',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/')
  async function create(title:string){
    await page.getByRole('button',{name:'New report',exact:true}).click()
    const dialog=page.getByRole('dialog')
    await dialog.getByLabel('Report title').fill(title)
    await dialog.getByLabel('Project',{exact:true}).fill('Runner browser fixture')
    await dialog.getByLabel('Application URL').fill('https://example.com')
    await dialog.getByLabel('Current build').fill('fixture-a')
    await dialog.getByLabel('Reported behavior').fill('Controlled fixture report; no real application was tested.')
    await dialog.getByLabel('Expected behavior').fill('Export a CSV')
    await dialog.getByRole('button',{name:'Save report',exact:true}).click()
    await expect(dialog).not.toBeVisible()
    await page.getByRole('tab',{name:'Agent context',exact:true}).click()
  }
  await create(`Runner fixture ${Date.now()}`)
  const panel=page.getByRole('region',{name:'Agent investigation',exact:true})
  await expect(panel.getByRole('button',{name:'Start Hermes investigation'})).toBeEnabled()
  await panel.getByRole('button',{name:'Start Hermes investigation'}).click()
  await expect(panel.getByRole('status')).toHaveText(/Queued|Submitting to Hermes|Investigating/)
  await page.reload()
  await page.getByRole('tab',{name:'Agent context',exact:true}).click()
  await expect(panel.getByRole('status')).toHaveText('Result ready for review',{timeout:20_000})
  await expect(panel).toContainText('Controlled fixture proposal')
  await expect(panel).toContainText('42')
  await expect(panel).toContainText('Not reported')
  await expect(panel).toContainText('has not been published as an observation')
  await page.screenshot({path:'test-results/runner-artifacts/result-desktop.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/runner-artifacts/result-mobile.png',fullPage:true,animations:'disabled'})
  await page.setViewportSize({width:1440,height:960})
  await create(`Hold fixture ${Date.now()}`)
  await panel.getByRole('button',{name:'Start Hermes investigation'}).click()
  await expect(panel.getByRole('status')).toHaveText('Investigating',{timeout:15_000})
  await panel.getByRole('button',{name:'Request stop'}).click()
  await expect(panel.getByRole('status')).toHaveText('Stopped',{timeout:15_000})
  expect(errors).toEqual([])
})
