import { test, expect } from '@playwright/test'

test('session history saves direction, survives reload, and continues without starting an agent', async ({ page }) => {
  const title = `Context mission ${Date.now()}`
  const project = `Session project ${Date.now()}`
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  let dispatches = 0; page.on('request', r => { if (r.method() === 'POST' && /\/runs$/.test(r.url())) dispatches++ })
  await page.goto('/?view=sessions')
  await page.getByRole('button', { name: 'New session', exact: true }).click()
  await page.getByLabel('Session title', { exact: true }).fill(title)
  await page.getByLabel('Project', { exact: true }).fill(project)
  await page.getByLabel('First prompt', { exact: true }).fill('Improve context quality without losing evidence.')
  await page.getByRole('button', { name: 'Create session', exact: true }).click()
  await expect(page.getByRole('heading', { name: title, exact: true })).toBeVisible()
  await page.getByLabel('Add direction to this session').fill('Preserve the source IDs and revoked-memory checks.')
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Note saved.' })).toBeVisible()
  const original = page.url()
  await page.reload()
  await expect(page.getByLabel('Saved conversation')).toContainText('Preserve the source IDs')
  await page.getByRole('button', { name: `Preview ${title}`, exact: true }).click()
  await expect(page.getByLabel('Agent session history')).toContainText('First prompt · preview')
  await page.getByLabel('Search sessions').fill('no matching session anywhere')
  await expect(page.getByText('No sessions match these filters.')).toBeVisible()
  await page.getByLabel('Search sessions').fill('')
  await page.getByLabel('Session project').selectOption(project)
  await expect(page.getByLabel('Agent session history')).toContainText('1 saved')
  await page.getByRole('button', { name: 'Continue in new session', exact: true }).click()
  await page.getByLabel('First prompt', { exact: true }).fill('Test context selection against held-out cases.')
  await page.getByRole('button', { name: 'Create session', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Open parent session' })).toBeVisible()
  await page.getByRole('button', { name: 'Open parent session' }).click()
  await expect(page).toHaveURL(original)
  await expect(page.getByLabel('Saved conversation')).toContainText('Preserve the source IDs')
  await expect(page.getByLabel('Agent work')).toContainText('Not measured')
  await page.screenshot({ path: 'test-results/session-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Agent work', exact: true }).click()
  await expect(page.getByLabel('Agent work', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Conversation', exact: true }).click()
  await expect(page.getByLabel('Add direction to this session')).toBeVisible()
  await page.screenshot({ path: 'test-results/session-mobile.png', fullPage: true })
  for (const width of [390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  expect(dispatches).toBe(0); expect(errors).toEqual([])
})

test('a lost note response can be reconciled after reload without a duplicate', async ({ page }) => {
  await page.goto('/?view=sessions')
  await page.getByRole('button', { name: 'New session', exact: true }).click()
  await page.getByRole('button', { name: 'Use our context improvement mission' }).click()
  await page.getByRole('button', { name: 'Create session', exact: true }).click()
  await expect(page.getByLabel('Add direction to this session')).toBeVisible()
  let lost = false
  await page.route('**/work-sessions/*/notes', async route => {
    if (!lost) { lost = true; await route.fetch(); await route.abort('failed') } else await route.continue()
  })
  await page.getByLabel('Add direction to this session').fill('Only one copy of this note.')
  await page.getByRole('button', { name: 'Save note', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Retry session save' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Retry session save' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Note saved.' })).toBeVisible()
  await expect(page.getByLabel('Saved conversation').getByText('Only one copy of this note.', { exact: true })).toHaveCount(1)
})

test('linked work keeps local validation and recorded context separate from session notes', async ({ page }) => {
  const report = await page.request.post('/api/v1/cases', { data: { title: 'Session linked-work fixture', project: 'Session work fixture', url: 'https://example.com', description: 'Controlled fixture, no live application tested.', expected: 'Show attributable recorded work.', build: 'fixture-build' } })
  expect(report.ok()).toBe(true)
  const item = await report.json()
  const created = await page.request.post('/api/v1/work-sessions', { data: { request_id: `linked-${Date.now()}`, title: 'Inspect context evidence', project: item.project, prompt: 'Preserve this direction independently of the recorded run.', case_id: item.id } })
  expect(created.ok()).toBe(true)
  const s = await created.json()
  const fixture = { id: 'RUN-session-fixture', case_id: item.id, case_revision: 1, owner_version: 1, build: item.build, version: 1, execution_kind: 'local_validation', status: 'completed', detail: 'Fixture validation recorded by a local inspector.', created_at: item.created_at, checked_at: item.created_at, deadline: item.created_at, max_seconds: 120, remote_id: null, output: 'Fixture result, not a live Hermes run.', usage: { total_tokens: 1200, cost_usd: 0.01 }, stop_requested: false, context_stale: true, context: { source_event_ids: ['fixture-event'], inspection: { inspector: 'Fixture inspector' } }, events: [] }
  await page.route(`**/cases/${item.id}/runs`, r => r.fulfill({ json: [fixture] }))
  await page.route('**/runs/RUN-session-fixture/*', r => r.fulfill({ json: { items: [], next_cursor: null } }))
  await page.goto(`/?view=sessions&session=${s.id}`)
  const work = page.getByLabel('Agent work', { exact: true })
  await expect(work).toContainText('Local validation record')
  await expect(work).toContainText('This run\'s context is stale.')
  await work.getByText('Context used by this run', { exact: true }).click()
  const packet = work.locator('details').filter({ has: page.getByText('Context used by this run', { exact: true }) }).locator('pre')
  await expect(packet).toContainText('fixture-event')
  await expect(packet).not.toContainText('Preserve this direction')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await page.screenshot({ path: 'test-results/session-dark-linked.png', fullPage: true })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 320, height: 844 })
  await page.getByRole('button', { name: 'Agent work', exact: true }).click()
  await expect(work).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await work.getByRole('button', { name: 'Open agent controls' }).click()
  await expect(page).toHaveURL(new RegExp(`view=agents.*case=${item.id}`))
})
