import { test, expect } from '@playwright/test'

test('library filters tools and persists the selection consumed by new terminal sessions', async ({ page, request }) => {
  const endpoint = 'http://127.0.0.1:8180/api/v1/tool-profile'
  const original = await (await request.get(endpoint)).json()
  try {
    await page.goto('/?view=connections')
    const library = page.getByRole('region', { name: 'Agent tools library' })
    await expect(library.locator('article')).toHaveCount(8)
    await page.getByRole('button', { name: 'Memory', exact: true }).click()
    await expect(library.locator('article')).toHaveCount(1)
    const trigger = page.getByRole('button', { name: 'Configure memory' })
    await trigger.click()
    const dialog = page.getByRole('dialog', { name: 'Mem0 memory' })
    await expect(dialog).toContainText('does not connect an account, start a model, or change Hermes')
    await dialog.getByRole('button', { name: original.mem0 ? 'Disable for new Pi sessions' : 'Enable for new Pi sessions', exact: true }).click()
    await expect(dialog.getByRole('status').filter({ hasText: /existing sessions/i })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(trigger).toBeFocused()
    await page.reload()
    await expect(library.locator('article').filter({ has: page.getByRole('heading', { name: 'Mem0 memory' }) })).toContainText(original.mem0 ? 'Not enabled in Pi' : 'Enabled for new Pi sessions')
    expect((await (await request.get(endpoint)).json()).mem0).toBe(!original.mem0)
    await page.getByLabel('Search tools').fill('missing tool fixture')
    await expect(page.getByText('No tools match this view')).toBeVisible()
    await page.getByRole('button', { name: 'Show all tools' }).click()
    await expect(library.locator('article')).toHaveCount(8)
    await page.screenshot({ path: 'test-results/tool-library-desktop.png', fullPage: true })
    await page.setViewportSize({ width: 320, height: 844 })
    await trigger.click()
    expect(await dialog.evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: 'test-results/tool-library-mobile.png' })
  } finally {
    const current = await (await request.get(endpoint)).json()
    const restored = await request.put(endpoint, { data: { version: current.version, mem0: original.mem0 } })
    expect(restored.ok()).toBe(true)
  }
})

test('failed selection requires reconciliation, and guest users cannot enable tools', async ({ page }) => {
  await page.goto('/?view=connections')
  await page.getByRole('button', { name: 'Configure memory' }).click()
  const dialog = page.getByRole('dialog', { name: 'Mem0 memory' })
  await page.route('**/api/v1/tool-profile', route => route.request().method() === 'PUT' ? route.fulfill({ status: 409, json: { error: 'Tool selection changed.' } }) : route.continue())
  const toggle = dialog.getByRole('button', { name: /^(Enable|Disable) for new Pi sessions$/ })
  await toggle.click()
  await expect(dialog.getByRole('alert')).toContainText('Refresh the saved selection')
  await expect(toggle).toBeDisabled()
  await dialog.getByRole('button', { name: 'Refresh saved selection' }).click()
  await expect(toggle).toBeEnabled()
  await page.route('**/api/v1/session', route => route.fulfill({ json: { mode: 'guest', authenticated: true } }))
  await page.reload()
  await page.getByRole('button', { name: 'Configure memory' }).click()
  await expect(dialog.getByRole('button', { name: 'Enable for new Pi sessions', exact: true })).toBeDisabled()
})
