import { test, expect } from '@playwright/test'

test('report, review memory, export, reject a stale handoff, and reload on mobile', async ({page}) => {
  const title = `Browser fixture: CSV export ${Date.now()}`
  const browserErrors: string[] = []
  page.on('pageerror', e => browserErrors.push(e.message))
  await page.goto('/')
  await page.getByRole('button',{name:'New report',exact:true}).click()
  const dialog=page.getByRole('dialog')
  await dialog.getByLabel('Report title').fill(title)
  await dialog.getByLabel('Project',{exact:true}).fill(`Browser fixture ${Date.now()}`)
  await dialog.getByLabel('Application URL').fill('https://example.com/reports')
  await dialog.getByLabel('Current build').fill('build-a')
  await dialog.getByLabel('Reported behavior').fill('Export produces no file after changing the date range.')
  await dialog.getByLabel('Expected behavior').fill('Download a CSV for the selected dates.')
  await dialog.getByRole('button',{name:'Save report',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button',{name:'Record observation',exact:true}).click()
  await dialog.getByLabel('Recorded by').fill('Browser fixture reviewer')
  await dialog.getByLabel('What you observed').fill('No download appeared after clicking Export.')
  await dialog.getByLabel('Steps taken').fill('1. Open Reports\n2. Change the date range\n3. Click Export')
  await dialog.getByLabel('Evidence URL').fill('https://example.com/fixtures/export-trace')
  await dialog.getByRole('button',{name:'Save observation',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await page.getByRole('button',{name:'Review for memory',exact:true}).click()
  await dialog.getByLabel('Reviewed by').fill('Browser fixture reviewer')
  await dialog.getByRole('checkbox').check()
  await dialog.getByRole('button',{name:'Publish reviewed memory',exact:true}).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.getByText('This observation is in project memory.')).toBeVisible()
  await page.getByRole('tab',{name:'Repair packet',exact:true}).click()
  await expect(page.locator('.packet-preview')).toContainText('No download appeared after clicking Export.')
  const downloadPromise=page.waitForEvent('download')
  await page.getByRole('button',{name:'Export Markdown',exact:true}).click()
  const download=await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^RR-.+\.md$/)
  await page.getByRole('tab',{name:'Agent context',exact:true}).click()
  await page.getByRole('button',{name:'Repair Reproduction, prior attempts, and missing code context',exact:true}).click()
  await page.getByRole('button',{name:'Prepare handoff',exact:true}).click()
  await expect(page.getByRole('region',{name:'Prepared handoff'})).toBeVisible()
  await page.getByRole('button',{name:'Check handoff freshness',exact:true}).click()
  await expect(page.getByText('Freshness checked',{exact:true})).toBeVisible()
  await page.getByLabel('Current build',{exact:true}).fill('build-b')
  await page.getByRole('button',{name:'Update build',exact:true}).click()
  await expect(page.getByRole('region',{name:'Prepared handoff'}).getByText('Outdated',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Check handoff freshness',exact:true}).click()
  await expect(page.getByRole('alert').filter({hasText:'The build or case evidence changed.'})).toBeVisible()
  await page.evaluate(()=>window.scrollTo(0,0))
  await page.screenshot({path:'test-results/context-stale-desktop.png',fullPage:true})
  await page.getByRole('button',{name:/Project memory/}).click()
  await expect(page.locator('.memory-card').filter({hasText:title})).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading',{name:title,exact:true}).last()).toBeVisible()
  await page.getByRole('tab',{name:'Agent context',exact:true}).click()
  await expect(page.getByLabel('Current build',{exact:true})).toHaveValue('build-b')
  await expect(page.getByRole('region',{name:'Prepared handoff'}).getByText('Outdated',{exact:true})).toBeVisible()
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:'test-results/context-mobile.png',fullPage:true})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(browserErrors).toEqual([])
})
